name: Build Release Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.3.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-release:
    name: Build and Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format. Use v1.2.3 format."
            exit 1
          fi
          echo "Building release for version: $VERSION"

      - name: Create Tag
        run: |
          git config user.name "Esteban Puerta"
          git config user.email "epuer94@gmail.com"
          git tag -a "${{ github.event.inputs.version }}" -m "Release ${{ github.event.inputs.version }}" || echo "Tag already exists"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Summary
        run: |
          echo "## Release ${{ github.event.inputs.version }} Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "wget -qO- https://github.com/cloudshipai/ship/releases/download/${{ github.event.inputs.version }}/ship_\$(uname -s)_\$(uname -m).tar.gz | tar xz && sudo mv ship /usr/local/bin/" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[View Release](https://github.com/cloudshipai/ship/releases/tag/${{ github.event.inputs.version }})" >> $GITHUB_STEP_SUMMARY