name: Update Changelog

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
          preset: 'conventionalcommits'
          tag-prefix: 'v'
          release-count: 0
          skip-version-file: true
          skip-commit: false
          create-summary: false

      - name: Commit Changelog
        run: |
          git config --local user.email "epuer94@gmail.com"
          git config --local user.name "Esteban Puerta"
          git add CHANGELOG.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update changelog for release"
            git push origin main
          fi